<div class="importCompleteHeader">
	<?=$page->importStatus?>
</div>
<div class="importCompleteMessage">
	<?=$page->insertCounter?> record<?=$page->successPlural?> imported successfully. <?=$page->failedMessage?>
</div>
<? if (!empty($page->tmp)) { ?>
	<div class="importCompleteErrorHolder">
		<div class="importCompleteDownloadHolder">
			A csv file that only contains your failed imports is available
			<a href="<?=WEB_PATH?>/download.php?fileType=csv&feature=importer&file=<?=$page->tmp?>">here</a>. Your Welcome.
		</div>
		<div>
			In the downloaded file, fix the issues described below and try importing again.
		</div>
		<div class="importCompletePaddingBottom"></div>
	</div>
<? } ?>