<div class="header">
	 Let's match fields to ensure your import is 100% accurate.
</div>
<div class="matchTitle">
	<div class="matchColumns">
		CSV Columns
	</div>
	<div class="matchArrowHolder">
		<img src="../imgs/overArrow.jpg" class="matchArrow" />
	</div>
	<div class="matchTables">
		Our Fields
	</div>
</div>
<div class="matchBody">
	<? foreach ($page->data['csvColumns'] as $csv) { ?>
		<div class="matchRow">
			<div class="matchCsvDisplayName">
				<?=$csv['displayName']?>
			</div>
			<div class="rightFloat">
				<div class="matchHolder">
					<select id="<?=$csv['name']?>" name="<?=$csv['displayName']?>" class="matchSelect">
						<? foreach ($page->data['tableColumns'] as $table) { ?>
							<? $selected = ((stripos($table, $csv['displayName']) !== FALSE) || str_replace(' ', '', $table) == $csv['match']) ? "selected" : ""; ?>
							<option value="<?=str_replace(' ', '', $table)?>" <?=$selected?>><?=$table?></option>
						<? } ?>
					</select>
				</div>
				<div class="matchImageHolder">
					<img src="<?=WEB_PATH?>/imgs/<?=$csv['image']?>" id="<?=$csv['name']?>_image" class="matchImage" title="<?=$csv['title']?>">
				</div>
			</div>
		</div>
	<? } ?>
	<div class="noteHolder">
		<span class="bold">Note:</span> Unmatched columns will not be imported.
	</div>
</div>

<div>
	<input type="hidden" name="page" value="match" />
</div>