<div class="header">
	What are you importing?
</div>
<div class="uploadFileInputHolders">
	<select name="importType">
		<option value="select">Select</option>
		<? foreach ($page->supportedTables as $validName => $displayName) { ?>
		<option value="<?=$validName?>"><?=$displayName?></option>
		<? } ?>
	</select>
</div>
<div class="header">
	Select a csv file to import
</div>
<div class="uploadFileInputHolders">
	<input type="file" name="csv" class="file" />
</div>
<div class="header" style="font-weight: bold;">
	Import Memory
</div>
<div class="description">
	<div>
		We remember prior imports to improve auto matching and speed up the import process.
		Would you like Import Memory turned on for this import?
	</div>
	<div class="uploadFileInputHolders">
		<input type="checkbox" name="autoMatching" checked/> Import Memory
	</div>
</div>
<input type="hidden" name="page" value="upload" />