<div class="header">
	What are you importing?
</div>
<div style="margin-top: 10px;">
	<select name="importType">
		<option value="select">Select</option>
		<option value="User">Users</option>
		<option value="Weapon">Weapons</option>
	</select>
</div>
<div class="header">
	Select a csv file to import
</div>
<div style="margin-top: 10px;">
	<input type="file" name="csv" />
</div>
<div>
	<input type="hidden" name="page" value="upload" />
</div>